### ISSUE TITLE
Custom slf4j logger within wrapped jar

### ISSUE THREAD

**Issue by UnAfraid** [TheBoegl/gradle-launch4j#40]
As title says

Whenever you build far jar and wrap the jar within the .exe custom loggers aren't discovered somehow
```
C:\Users\UnAfraid\Desktop>java -jar ClientEditorUI.exe
2017-01-03 00:03:58,251 ERROR Error processing element GUILogger: CLASS_NOT_FOUND
2017-01-03 00:03:58,292 ERROR Unable to locate appender JavaFXLogger for logger
```
When running the jar:
```
C:\Users\UnAfraid\Desktop>java -jar ClientEditorUI.jar
[00:03:45] [INFO] MainController: Welcome to the Client Editor!
```
When you do java -jar the.exe it fails to find it, but when you do java -jar the.jar it works.
Whenever you open the exe with 7z manager lets say all is there the files are there, both config file and the compiled custom logger appender

Here's another report of the very same issue http://stackoverflow.com/questions/39866144/in-launch4j-wrapper-my-custom-log4j2-appender-cant-be-found

My repository with test case https://github.com/UnAfraid/Launch4jPlusSLF4j

Whenever i do `dontWrapJar = true` it works fine.

**Comment by TheBoegl** [comment]
This seems to me like a problem from log4j2 with your created wrapped jar. If you call the executable with `java -Dorg.apache.logging.log4j.simplelog.StatusLogger.level=TRACE -classpath "pathToYourExecutable"` you see more details. Even if you set the `log4j.configurationFile` property programmatically or on the command line it does not help.
Seems like an log4j2 issue to me.

**Comment by UnAfraid** [comment]
Its quite weird, how the jar works but the exe doesn't

**Comment by TheBoegl** [comment]
You are not merging the `META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat` files, hence, the `GUILogger.class` is not found.

As a work around use the [gradle shadow plugin](/johnrengelman/shadow). This will result in an error like [this on on SO](http://stackoverflow.com/questions/25065580/log4j2-custom-plugins-annotation-processing-with-maven-assembly-plugin) which was fixed in [maven shaded log4j-transformer](/edwgiz/maven-shaded-log4j-transformer). See [this gist](https://gist.github.com/TheBoegl/695eaa6837764bcfb08137a48d873c60) for a possible solution.

**Comment by UnAfraid** [comment]
The gist worked, thanks!
