### ISSUE TITLE
Launch4j and FatJar

### ISSUE THREAD

**Issue by simonharrer** [TheBoegl/gradle-launch4j#6]
We build a fat jar using the fatJar gradle plugin. We would like to convert this jar into a single exe file with your plugin. How can I deactivate the copyL4jLib task? Because this is not required for my task - I am only interested in copying a single jar file over.

**Comment by byronpdx** [comment]
I would like that as well. I use a different structure where the libraries are dynamically loaded at runtime to allow for added functionality and to allow the same library files to be used for a variety of applications. I also do not need to have the libraries gathered and I would also like to be able to have the main class jar file at the same level as the executable rather than with the libraries. That allows the launch of the program from either the executable or from the jar file. My structure looks like:

    Program_Folder
      program.exe
      program.jar
    Another_Program
      another.exe
      another.jar
    Libraries
      utility
        utility.jar
      application
        app_library.jar
        user_library.jar
      logging
        slf4j.jar
        logback.jar

This allows both programs to use the same jar files as well as the special application jars in the Libraries/application folder.

The launcher does not need to know the full class path as that is done at launch by the program itself by dynamically loading the libraries at run time. The actual usage of the libraries is driven by dependency injection. 

A way to achieve this would be wonderful. Thanks so much for providing help.

**Comment by TheBoegl** [comment]
@simonharrer If you like to skip the copyL4jLib task, have you tried the ***gradle way*** and copy your jar by hand?
    
    copyL4jLib.enabled = false
    createExe.doFirst {
        // copy your configuration here to the launch4j folder
    }
    
I'm not certain if this workaround is meaningful or should be implemented in the plugin, tough I'd tend to the former...

@byronpdx If you use different configurations for your libraries (e.g. utility, application, logging) and configure the launch4j plugin to execute your copy task in between the run and the copy task, this should be doable, if your classpath/manifest is correctly set.

**Comment by simonharrer** [comment]
@TheBoegl thank you for your fast reply. We are currently executing the copyL4jLib task, but ignoring its output and configuring the launch4j task so that it links directly to the fatJar. It is similar to your proposed workaround - but I keep the enabled flag in mind (again what learned ;-).

How difficult would it be to make the *from* part of the copyL4jLib configurable? So that I can override the defaults if I like, but I do not have to as many users can work with the sensible defaults.

**Comment by TheBoegl** [comment]
I'll look into a more configurable solution for the copyL4jLib task.

**Comment by TheBoegl** [comment]
@simonharrer Will this suite your needs?

**Comment by simonharrer** [comment]
Awesome! This fits my use case perfectly.

**Comment by byronpdx** [comment]
Thanks for combining two great utilities. I have got this to work for me and it is great. Still on the learning curve for gradle so don't always know all the ins and outs.
